version: '3.9'
services:
  samba:
    container_name: samba
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
        - GROUP=${GROUP}
        - PUID=${PUID}
        - PGID=${PGID}
    volumes: # add your local mappings here
      - /mnt/sample:/mnt/sample
      - ./confs:/config # this is required
    ports:
      - 135:135/tcp
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
